###############################################################################
#
# $Id: Makefile 11904 2015-09-07 15:00:51Z aidan $
#
# Copyright 2006-2008 Innocore Gaming Limited.
# All rights reserved.
#
# Description:
# Makefile for DPCI demos
#
###############################################################################

SUBDIRS		= dpci_core \
			dpci_mem \
			dpci_serial

include $(SRCROOT)/build/rules.mk
