###############################################################################
#
# $Id: Makefile 12882 2016-11-11 03:45:46Z aidan $
#
# Copyright 2005-2016 Advantech Co. Ltd.
# All rights reserved.
#
# Description:
# Makefile for DirectPCI serial test.
#
###############################################################################

EXES=uart_test
BUILDS = DEBUG
uart_test_OBJS =	uart_test.o

include $(SRCROOT)/build/rules.mk
