###############################################################################
#
# $Id: Makefile 3452 2008-04-11 12:46:38Z aidan $
#
# Copyright 2006-2008 Innocore Gaming Limited.
# All rights reserved.
#
# Description:
# Makefile for DPCI demos
#
###############################################################################

SUBDIRS = dpci_core dpci_sram dpci_rom dpci_serial

include $(SRCROOT)/build/rules.mk
